# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [Godaddy, Cola, CW35, Laff ]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username opensea.com
ko_fi: # Replace with a single Ko-fi username Mario nerds 
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry https://Smithla.slack.com
liberapay: # Replace with a single Liberapay username https://justinfamily.family.blog/ https://vm.tiktok.com/gQEfYG/
issuehunt: # Replace with a single IssueHunt iamjustin3687@gmail.com
otechie: # Replace with a single Otechie username https://cloud.google.com/appengine/docs/flexible/java/configuring-the-web-xml-deployment-descriptor
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['Https://Mycokerewards', 'https://justinfamily.family.blog/']
